# -*- coding: utf-8 -*-
"""6.2.1. Eliminando valores duplicados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQ68gLi4lf5fN6BsmRfkylPjbkEkgLiN
"""
'''
Clase:        6
Tema:         Listas
Ejercicio:    6.2.1
Descripcion:  Usando el set se ocupa para no repetir los numeros, los cuales se convierten

Autor:        Diego Emilio Garcia Montano
Fecha:        2025-05-30
Estado:       [Terminado]
'''

entrada = input().split()
vistos = {}
resultado = []

for num in entrada:
    if num not in vistos:
        resultado.append(num)
        vistos[num] = True

print(" ".join(resultado))