# -*- coding: utf-8 -*-
"""6.3.1 Numeros lideres

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13619zi7spxBX7CkEX6v8ujnsvt7K0q2i
"""

'''
Clase:        9
Tema:         Listas
Ejercicio:    6.2.1
Descripcion:  Usando el set se ocupa para no repetir los numeros, los cuales se convierten

Autor:        Diego Emilio Garcia Montano
Fecha:        2025-05-30
Estado:       [Terminado]
'''
numeros = input().split()
resultado = []
mayor = -1

for i in range(len(numeros) - 2, -1, -1):
    num = int(numeros[i])
    if num > mayor:
        resultado.append(str(num))
        mayor = num

print(" ".join(reversed(resultado)))