# -*- coding: utf-8 -*-
"""6.3.1 Numeros lideres

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13619zi7spxBX7CkEX6v8ujnsvt7K0q2i
"""

'''
Clase:        6
Tema:         Listas
Ejercicio:    6.3.1
Descripcion:  se listan los numeros que son mayores a los que estan a su derecha

Autor:        Diego Emilio Garcia Montano
Fecha:        2025-06-01
Estado:       [Terminado]
'''
numeros = input().split()
resultado = []
mayor = -1

for i in range(len(numeros) - 2, -1, -1):
    num = int(numeros[i])
    if num > mayor:
        resultado.append(str(num))
        mayor = num

print(" ".join(reversed(resultado)))