# -*- coding: utf-8 -*-
"""1.3.2. Generador del correo de Key

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bDQna2JQhtIoxIuw7RL5c05CVuJksn96
"""

nombre = input("Ingresa tu nombre completo: ")

nombre_separado = nombre.split()


primer_nombre = nombre_separado[0]
primer_apellido = nombre_separado[2]

correo = primer_nombre.lower() + '.' + primer_apellido.lower()+'@keyinstitute.edu.sv'

print("El correo que se debe asignar al usuario ingresado es:",correo)