# -*- coding: utf-8 -*-
"""2.3.2. Cálculo de impuesto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Vxk4aTcd0WOLVsLwQ4qy0fxq0qwZt9j
"""

unidades_consumidas = 150

if unidades_consumidas:
    if unidades_consumidas > 0 < 100:
        print('sin impu')

if unidades_consumidas:
    if unidades_consumidas > 100 < 200:
        impuestos150 = unidades_consumidas*0.5
        print(impuestos150)

unidades_consumidas = 150
if unidades_consumidas >= 0 and unidades_consumidas <= 100:
    impuesto = 0
    print(f"Sin impuestos: {impuesto}")
elif unidades_consumidas >= 101 and unidades_consumidas <= 200:
    impuesto = unidades_consumidas * 0.5
    print(f"Impuesto aplicado: {impuesto}")
elif unidades_consumidas >= 201:
    impuesto = unidades_consumidas * 0.7
    print(f"Impuesto aplicado: {impuesto}")

unidades_consumidas = 220

if unidades_consumidas <= 100:
  impuesto = 0
elif unidades_consumidas <= 200:
  impuesto = unidades_consumidas * 0.5
else:
  impuesto = unidades_consumidas * 0.7

print("Impuesto aplicado: $",impuesto)