# -*- coding: utf-8 -*-
"""5.4.1. ¡Adivina el número!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CAE6hPsuJI_zFtysPhIOBHXg4XG8d2Au
"""

'''
Clase:        5
Tema:         bucles
Ejercicio:    5.4.1
Descripcion:  Usando un bucle para adivinar un numero secreto

Autor:        Diego Emilio Garcia Montano
Fecha:        2025-05-31
Estado:       [Terminado]
'''

numero_secreto = 3

while True:

  numero_adivinado = int(input('Ingresa un numero entre 1 y 100:'))

  if numero_adivinado < numero_secreto:
    print('El numero secreto es mayor')


  elif numero_adivinado > numero_secreto:
    print('El numero secreto es menor')


  elif numero_adivinado == numero_secreto:
    print('!Felicidades! Has adivinado el numero secreto')
    break