# -*- coding: utf-8 -*-
"""5.4.2. Sumador de valores posicionales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZKC-uHmZ7A1csCZVicWdSVW1D510CWY
"""

'''
Clase:        Clase 5
Tema:         bucles
Ejercicio:    5.4.
Descripcion:  Usando un bucle sumar los digitos de un numero

Autor:        Diego Emilio Garcia Montano
Fecha:        2025-05-31
Estado:       [Terminado]
'''

numero = input("Ingresa un numero: ")

print("Proceso de reduccion para", numero + ":")

while len(numero) > 1: #el bucle va a seguir hasta que tenga un solo digito
    suma = 0
    for digito in numero:
        suma += int(digito)
    print(numero, "=", suma)
    numero = str(suma)

print("El resultado final es:", numero)