# -*- coding: utf-8 -*-
"""10.2.1. Diagonal principal y secundaria

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNMZn6wFujLSzkp2otmocwJMRdRIV_JN
"""

'''
Clase:        10
Tema:         Matrices
Ejercicio:    10.2.1
Descripcion:  Ejercicios de matriz

Autor:        Diego Emilio Garcia Montano
Fecha:        2025-06-13
Estado:       [Terminado]
'''

tamaño = int(input("Ingrese la dimension de la matriz : "))

matriz = []

print('Ahora ingrese cada fila de la matriz, separando los números con comas (,):')
for numero_fila in range(tamaño):
    fila_ingresada = list(map(int, input(f"Fila ingresada {numero_fila + 1}: ").split(',')))
    matriz.append(fila_ingresada)

elementos_diagonal_principal = [matriz[i][i] for i in range(tamaño)]
elementos_diagonal_secundaria = [matriz[i][tamaño - 1 - i] for i in range(tamaño)]

print("Diagonal principal:", elementos_diagonal_principal)
print("Diagonal secundaria:", elementos_diagonal_secundaria)