# -*- coding: utf-8 -*-
"""10.3.1. Matriz simétrica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mzuesiGejYatoK0vZjPPhLsQJmKzRjTL
"""

'''
Clase:        10
Tema:         Matrices
Ejercicio:    10.3.1
Descripcion:  Ejercicios de matriz

Autor:        Diego Emilio Garcia Montano
Fecha:        2025-06-13
Estado:       [Terminado]
'''


tamaño = int(input())

matriz = []

for _ in range(tamaño):
    fila = list(map(int, input().split(',')))
    if len(fila) != tamaño:
        print("Error: la fila debe tener exactamente", tamaño, "números.")
        exit()
    matriz.append(fila)

simetrica = True
for i in range(tamaño):
    for j in range(tamaño):
        if matriz[i][j] != matriz[j][i]:
            simetrica = False
            break

if simetrica:
    print("La matriz es simétrica")
else:
    print("La matriz no es simétrica")