# -*- coding: utf-8 -*-
"""10.3.2. Juego del entorno

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1urDLtL2I2-ShujM76Zuju5eJGOnYNZ-h
"""

'''
Clase:        10
Tema:         Matrices
Ejercicio:    10.3.2
Descripcion:  Ejercicios de matriz

Autor:        Diego Emilio Garcia Montano
Fecha:        2025-06-13
Estado:       [Terminado]
'''
n = int(input())
m = int(input())

matriz = []
for _ in range(n):
    fila = list(map(int, input().split(',')))
    matriz.append(fila)

direcciones = [(-1, -1), (-1, 0), (-1, 1),
               (0, -1),          (0, 1),
               (1, -1),  (1, 0),  (1, 1)]

resultado = []

for i in range(n):
    fila_resultado = []
    for j in range(m):
        suma = 0
        for dx, dy in direcciones:
            ni, nj = i + dx, j + dy
            if 0 <= ni < n and 0 <= nj < m:
                suma += matriz[ni][nj]
        fila_resultado.append(suma)
    resultado.append(fila_resultado)

for fila in resultado:
    print(fila)