# -*- coding: utf-8 -*-
"""2.3.1. Contraseña segura

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xVUuANdYzdcsMWjjqkIgmH7QzIQ9Q2TC
"""
'''
Clase:        2
Tema:         
Ejercicio:    2.3.1
Descripcion:  

Autor:        Diego Emilio Garcia Montano
Fecha:        2025
Estado:       [Terminado]
'''
txt = input('Ingrese una contrasena: ')


if len(txt) < 8:
    print('Contrasena no segura')


if txt:
    mayuscula=any(c.isupper() for c in txt)
#print(mayuscula)


if txt:
    caracteres=any(c.isdigit() for c in txt)
#print(caracteres)


if txt:
    if caracteres and mayuscula == True:
        print('Contrasena segura')

else:
    print('Contrasena no segura')