# -*- coding: utf-8 -*-
"""1.3.1. Automatizando el cálculo de la propina

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dOwMjTVoVhhXS5IuCRkx38_nsQ7izujA
"""

total_cuenta = float(input("Introduce el total de la cuenta: "))
porcentaje_propina = int(input("Introduce el porcentaje de propina (ej. 10, 15, 20): "))

propina = total_cuenta * (porcentaje_propina / 100)
total_a_pagar = total_cuenta + propina

print('Total de la cuenta: $', total_cuenta)
print('Propina: $', propina)
print('Total de la cuenta con propina: $', total_a_pagar)