# -*- coding: utf-8 -*-
"""6.2.1. Eliminando valores duplicados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQ68gLi4lf5fN6BsmRfkylPjbkEkgLiN
"""

entrada = input().split()
vistos = {}
resultado = []

for num in entrada:
    if num not in vistos:
        resultado.append(num)
        vistos[num] = True

print(" ".join(resultado))